In [19]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
X.shape, y.shape

((400, 4096), (400,))

In [20]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, random_state=42)
X_tr.shape, X_te.shape, y_tr.shape, y_te.shape

((300, 4096), (100, 4096), (300,), (100,))

In [21]:
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier()
modelo.fit(X_tr, y_tr)
knn_pr = modelo.predict(X_te)
knnhits = knn_pr == y_te
knnhits, sum(knnhits)/len(knnhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False, False,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.83)

In [22]:
from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB()
modelo.fit(X_tr, y_tr)
gnb_pr = modelo.predict(X_te)
gnbhits = gnb_pr == y_te
gnbhits, sum(gnbhits)/len(gnbhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
        False]),
 0.81)

In [23]:
from sklearn.linear_model import Perceptron
modelo = Perceptron()
modelo.fit(X_tr, y_tr)
per_pr = modelo.predict(X_te)
perhits = per_pr == y_te
perhits, sum(perhits)/len(perhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
        False]),
 0.78)

In [24]:
import numpy as np
hits = np.stack((knnhits, gnbhits, perhits))

hits.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ T

In [25]:
y_pr = np.stack((knn_pr, gnb_pr, per_pr))
y_pr.T

array([[20, 20, 20],
       [28, 28, 28],
       [ 3,  3,  3],
       [21, 21, 21],
       [ 9,  9,  9],
       [ 8,  8,  8],
       [32, 32, 32],
       [ 9,  9,  9],
       [26, 26, 26],
       [12, 16, 28],
       [ 0,  0,  0],
       [36, 36, 36],
       [ 5,  5,  8],
       [ 7, 15,  7],
       [13, 13, 13],
       [ 4, 34, 29],
       [25, 27, 25],
       [37, 37, 37],
       [23, 23, 23],
       [38, 38, 38],
       [ 7, 15,  7],
       [ 1,  1,  1],
       [ 4, 39, 39],
       [25, 27, 25],
       [ 0,  0,  0],
       [ 3, 39, 39],
       [11, 11, 11],
       [22, 22, 22],
       [26, 26, 26],
       [10, 15, 10],
       [29, 39, 39],
       [29, 19, 19],
       [26, 26, 26],
       [ 5,  5, 29],
       [20, 23, 23],
       [11, 11, 11],
       [12, 39, 11],
       [20, 34, 34],
       [15, 15, 15],
       [14, 14, 14],
       [38, 38, 38],
       [ 5,  5, 29],
       [ 7,  9,  7],
       [ 2,  2, 36],
       [ 8,  8,  8],
       [28, 38, 28],
       [14, 14, 14],
       [18, 1

In [26]:
from scipy import stats
y_pr = stats.mode(y_pr)[0][0]
vohits = y_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

Combinação de classificadores

In [27]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('naivebayes', GaussianNB()),
    ('perceptron', Perceptron())
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [28]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
    ('knn1', KNeighborsClassifier(1)),
    ('knn2', KNeighborsClassifier(5)),
    ('knn3', KNeighborsClassifier(9)),
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True, False,  True,
         True,  True,  True, False, False,  True,  True,  True,  True,
        False, False, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
        False]),
 0.84)

In [29]:
from sklearn.tree import DecisionTreeClassifier
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('naivebayes', GaussianNB()),
    ('arvore', DecisionTreeClassifier())
])
modelo.fit(X_tr, y_tr)
vo_pr = modelo.predict(X_te)
vohits = vo_pr == y_te
vohits, sum(vohits)/len(vohits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.81)

In [31]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
dt_pr = modelo.predict(X_te)
dthits = dt_pr == y_te
dthits, sum(dthits)/len(dthits)

(array([False,  True, False,  True,  True, False,  True,  True,  True,
        False, False,  True,  True, False, False, False, False, False,
         True, False,  True, False, False, False, False, False, False,
        False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False,  True, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True,  True, False, False, False,  True, False,
        False, False,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False, False,  True, False,
        False]),
 0.4)

Diversificação por reamostragem

In [32]:
from sklearn.ensemble import BaggingClassifier
modelo = BaggingClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]),
 0.64)

In [33]:
modelo = BaggingClassifier(DecisionTreeClassifier(), random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]),
 0.64)

Aumentando a aleatoriedade para aumentar a diversidade

In [34]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
        False,  True,  True, False,  True, False,  True,  True, False,
         True, False, False,  True, False,  True,  True,  True, False,
        False,  True, False,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True]),
 0.72)

In [35]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.89)

Random Forest é um Bagging de Árvores de Decisão

In [36]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
rf_pr = modelo.predict(X_te)
rfhits = rf_pr == y_te
rfhits, sum(rfhits)/len(rfhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.88)

Regularização do Bagging

In [37]:
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, max_features=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
bag_pr = modelo.predict(X_te)
baghits = bag_pr == y_te
baghits, sum(baghits)/len(baghits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.94)

Florestas extremamente aleatórias

In [38]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(X_tr, y_tr)
et_pr = modelo.predict(X_te)
ethits = et_pr == y_te
ethits, sum(ethits)/len(ethits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

Boosting

In [61]:
from sklearn.ensemble import AdaBoostClassifier 
#sensivel aos hiperparâmetros, ideal é utilizar junto com o gridsearch para selecionar os melhores parm
#modelo = AdaBoostClassifier(random_state=42)
#modelo = AdaBoostClassifier(GaussianNB(), random_state=42)
modelo = AdaBoostClassifier(DecisionTreeClassifier(splitter='random', max_depth=25), learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
ab_pr = modelo.predict(X_te)
abhits = ab_pr == y_te
abhits, sum(abhits)/len(abhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.91)

In [54]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25, splitter='random'), learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
ab_pr = modelo.predict(X_te)
abhits = ab_pr == y_te
abhits, sum(abhits)/len(abhits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.91)

In [62]:
import xgboost as xgb

modelo = XGBClassifier(use_label_encoder=False, random_state=42)
modelo.fit(X_tr, y_tr)
xgb_pr = modelo.predict(X_te)
xgbhits = xgb_pr == y_te
xgbhits, sum(xgbhits)/len(xgbhits)

ModuleNotFoundError: No module named 'xgboost'

In [57]:
from xgboost import XGBClassifier
modelo = XGBClassifier(colsample_bynode=0.01, learning_rate=0.15, random_state=42)
modelo.fit(X_tr, y_tr)
xgb_pr = modelo.predict(X_te)
xgbhits = xgb_pr == y_te
xgbhits, sum(xgbhits)/len(xgbhits)

ModuleNotFoundError: No module named 'xgboost'

In [58]:
import warnings
warnings.filterwarnings('ignore')

In [59]:
from sklearn.ensemble import StackingClassifier

voting = VotingClassifier([
        ('knn', KNeighborsClassifier()),
        ('naivebayes', GaussianNB()),
        ('perceptron', Perceptron())
    ])

modelo = StackingClassifier([
    ('voting', voting),
    ('extratrees', ExtraTreesClassifier(random_state=42)),
    ('randomforest', RandomForestClassifier(random_state=42))
], cv=3, passthrough=True)

modelo.fit(X_tr, y_tr) 
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [60]:
modelo = StackingClassifier([
    ('randomforest42', RandomForestClassifier(random_state=42)),
    ('randomforest43', RandomForestClassifier(random_state=43)),
    ('randomforest44', RandomForestClassifier(random_state=44))
], cv=3, passthrough=True)

modelo.fit(X_tr, y_tr) 
sc_pr = modelo.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [69]:
from sklearn.ensemble import StackingClassifier

stackclf = StackingClassifier([
    ('xt', ExtraTreesClassifier()),
    ('rf', RandomForestClassifier()),
    ('knn', KNeighborsClassifier())
], cv=3, passthrough=True)

stackclf.fit(X_tr, y_tr) 
sc_pr = stackclf.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [70]:
from sklearn.ensemble import StackingClassifier

stackclf = StackingClassifier([
    ('xt', ExtraTreesClassifier()),
    ('rf', RandomForestClassifier()),
    ('knn', KNeighborsClassifier())
], RandomForestClassifier())

stackclf.fit(X_tr, y_tr) 
sc_pr = stackclf.predict(X_te)
schits = sc_pr == y_te
schits, sum(schits)/len(schits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.94)